name: continuous integration

on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - '**.md'
  workflow_dispatch:

jobs:
  build:
  timeout-minutes: 30
  steps:
    - uses: actions/checkout@v3

    - name: test
      run: echo "hello world"

    - name: get system
      run: uname

